name: Generate Statistics

on:
  push:
    branches:
      - main
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    name: Generate Statistics JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install dependencies
        run: |
          cd website
          npm ci

      - name: Generate statistics
        run: |
          cd website
          npm run generate
          
          # Count various statistics
          total_yaml=$(find ../signatures/ -name "*.yml" -o -name "*.yaml" | wc -l)
          total_rats=$(find ../signatures/rats/ -name "*.yml" -o -name "*.yaml" 2>/dev/null | wc -l)
          total_trojans=$(find ../signatures/trojans/ -name "*.yml" -o -name "*.yaml" 2>/dev/null | wc -l)
          total_ransomware=$(find ../signatures/ransomware/ -name "*.yml" -o -name "*.yaml" 2>/dev/null | wc -l)
          total_other=$(find ../signatures/other/ -name "*.yml" -o -name "*.yaml" 2>/dev/null | wc -l)
          
          # Count mutexes from generated JSON
          total_mutexes=$(node -e "
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('public/data/malware.json', 'utf8'));
            const total = data.malware.reduce((sum, m) => sum + m.mutexes.length, 0);
            console.log(total);
          ")
          
          # Save statistics to file (for reference only, not used in README)
          cat > ../stats.json << EOF
          {
            "total_yaml": $total_yaml,
            "total_rats": $total_rats,
            "total_trojans": $total_trojans,
            "total_ransomware": $total_ransomware,
            "total_other": $total_other,
            "total_mutexes": $total_mutexes,
            "last_updated": "$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          }
          EOF

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stats.json
          git commit -m "Update statistics JSON (badges now generated on Cloudflare Pages)"
          git push 